### ISSUE TITLE
Splash pages give "Not found" error in Google cache

### ISSUE THREAD

**Issue by Ken-Lo** [gocardless/splash-pages#143]
All splash pages give a "Not found" error when viewed in Google's cache with Javascript enabled. With Javascript disabled, it works OK. Pages seem to be crawled correctly (so a fairly low priority fix).

![screen shot 2015-05-20 at 14 59 44](https://cloud.githubusercontent.com/assets/6426688/7727486/e198df4c-ff00-11e4-85e0-507bd8e309b4.png)
http://webcache.googleusercontent.com/search?q=cache:Z60paZAQ7wsJ:https://gocardless.com/+&cd=1&hl=en&ct=clnk&gl=uk

I suspect it's probably a weird conflict in the Javascript as the page is being accessed through path `/search?q=cache:Z60paZAQ7wsJ:https://gocardless.com/+&cd=1&hl=en&ct=clnk&gl=uk` (possibly, also an issue with cross-domain Javascript).

Probably not a major issue as it doesn't affect indexing (only seems to affect people viewing our website through a weird HTTP proxy, etc). Can probably be fixed by checking the hostname in bundle js? Though feel free to mark as Won't Fix if it's difficult to do or if it causes problems elsewhere.

**Comment by harrison** [comment]
Ugh this is annoying, will definitely be the query string. When js is enabled it will try and navigate to `/search`.. also the 404 page is really shit, opening an issue for this
