### ISSUE TITLE
`learn more about Pro` should probably be right-aligned?

### ISSUE THREAD

**Issue by samjewell** [gocardless/splash-pages#153]
On /features it currently looks like this:

![screen shot 2015-05-21 at 11 30 38](https://cloud.githubusercontent.com/assets/2903904/7746808/52da3366-ffad-11e4-8976-180bf26c7b51.png)

Pretty sure the link should be aligned with the right hand column in the table, no?

Code looks like this:
```
<td />
<td />
<td className='u-padding-As'>
  <a href='/pro' id='track-comparison-table-pro' className='u-color-primary'>
    Learn more about GoCardless Pro
  </a>
</td>
```

So it's already the third cell across in the table, but the problem is that the first 2 cells in the table basically have zero width.

I'm a bit of a noob to this repo - probably just quicker / easier for someone else to fix? Thanks guys!

**Comment by Ken-Lo** [comment]
@samjewell Nice spot! I don't know why this link is in a separate `<table>` to the stuff that's above it?
