### ISSUE TITLE
Have a better way of expressing intent using the <Translation> tag

### ISSUE THREAD

**Issue by Ken-Lo** [gocardless/splash-pages#168]
So far, there are four main categories of intent when using the `<Translation>` component in the splash pages.

1. **Country-specific info**
Showing information that's specific to a certain country. For example: UK-only case studies or FR merchant logos. This intent is well served by the `<Translation>` component:
    ```jsx
    <Translation locales='en-GB'>
      UK specific info, logos, etc.
    </Translation>
    <Translation locales='en-IE'>
      IE specific info, logos, etc.
    </Translation>
    etc
    ```

2. **Domestic scheme & currency specific info**
Show different information depending on the domestic DD scheme or currency in that country.
    ```jsx
    <Translation locales={['en-GB']}> // Bacs
      Bacs, Direct Debit Guarantee, collect £s, etc.
    </Translation>
    <Translation locales={['en']} exclude={['en-GB']}> // SEPA
      SEPA, SEPA Customer Protection, collect €, etc.
    </Translation>
```
Examples: 
 * [app/pages/faq/merchants/direct-debit/faq-merchants-direct-debit.en.js:11](https://github.com/gocardless/splash-pages/blob/dev/app/pages/faq/merchants/direct-debit/faq-merchants-direct-debit.en.js#L11)
  * [app/pages/faq/merchants/security/faq-merchants-security.en.js:64](https://github.com/gocardless/splash-pages/blob/dev/app/pages/faq/merchants/security/faq-merchants-security.en.js#L64)

  This probably breaks down once we start adding additional schemes or countries (it becomes an ever-growing list of locales to specify in every file). 

3. **Signup process dependent info**
Show different information depending on whether self-serve sign-up is available (e.g. start taking payments now or contact sales CTA). At present, the intent is specified as follows:
    ```jsx
     // Here, {['en-GB']} is a white list of locales who can sign up immediately
    <Translation locales={['en-GB']}>
      Start taking payments today
    </Translation>
    <Translation locales={['en']} exclude={['en-GB']}>
      Contact sales
    </Translation>
```

  Examples:
  * [app/pages/faq/merchants/signing-up/faq-merchants-signing-up.en.js:13](https://github.com/gocardless/splash-pages/blob/dev/app/pages/faq/merchants/signing-up/faq-merchants-signing-up.en.js#L13)
  * [app/pages/features/features.en.js:120](https://github.com/gocardless/splash-pages/blob/dev/app/pages/features/features.en.js#L120)

4. **Product dependent info**
Show different information depending on whether Basic/BasicPro is available in that country. So far, we specified the intent as follows:
    ```jsx
     // Here, {['en-GB', 'en-IE']} is a list of locales with Basic pricing
    <Translation locales={['en-GB','en-IE']}>
      We charge <Message message='pricing.per_transaction_amount_normal' /> capped at <Message message="pricing.cost_cap" />.
    </Translation>
    <Translation locales={['en']} exclude={['en-GB','en-IE']}>
      We charge you a <Message message='pricing.pro_monthly_fee' /> monthly fee and a fee for each transaction.
    </Translation>
```
  Example:
  * [app/pages/pricing/pricing.en.js#L11](https://github.com/gocardless/splash-pages/blob/dev/app/pages/pricing/pricing.en.js#L11)

  As a special case, [app/pages/features/features.en.js:421](https://github.com/gocardless/splash-pages/blob/dev/app/pages/features/features.en.js#L421) uses a further `<Translation>` block to show different screenshots depending on the dashboard version.

It would be good to update `<Translation>` so we can better express what the Translation is meant for.
Use case 1 is already well served with the current design.
Use case 2 probably requires a new component (especially if we want to handle more than 2 schemes)
Use cases 3 and 4 can potentially be solved by storing a central list somewhere (otherwise you need to manually go through all of the files to update the locale list when launching basic pricing or self-serve signup).

**Comment by harrison** [comment]
Think the simplest solution would be to create new wrapper components:

```js
<BacsTranslation>
...
</BacsTranslation>
```

```js
import Translation from '../translation/translation';

export default class BacsTranslation extends React.Component {
  displayName = 'BacsTranslation'

  static propTypes = {
    children: React.PropTypes.node.isRequired,
  }

  render() {
    return (
      <Translation locales={['en-GB']} {...this.props}>
        {this.props.children}
      </Translation>
    );
  }
}
```

**Comment by harrison** [comment]
What do you reckon?

**Comment by Ken-Lo** [comment]
@harrison Sounds good to me.

For no. 2, happy to have anything like `<BacsTranslation>`, `<IfBacs>`, `<Translation scheme='Bacs'>`, `<If LocalScheme={['Bacs']}>`, `<If LocalCurrency={['GBP']}>` or whatever is cleanest & makes the most sense :)

Things to bear in mind:
* We'll need to accommodate new schemes very soon (e.g. Autogiro)
* We should probably try to be as precise as possible when defining the tags e.g. `<AutogiroTranslation>` could be for Norway or Sweden.
* It's still possible to have info about SEPA in a `<BacsTranslation>` block (e.g. on the International Payments page, info about SEPA would appear in `<BacsTranslation>` whereas info about Bacs would appear in `<SepaTranslation>`. More precisely, the thing we're actually trying to say with the tag is: "if the local scheme is Bacs then show this information".
* Something like `<IfLocalScheme name='Bacs'>` is probably most flexible/precise?

For 3 and 4 (simple binary options), I guess probably easiest to solve with sth like `<IfSignupAvailable>`, `<IfBasicPricingAvailable>`?

**Comment by harrison** [comment]
yeah I like the `IfX` convention, would have to be one name, so `IfBacs`, `IfSignupAvailable` etc. Would you want to give a go at adding some when there's stuff to update/add? We're full steam on admin/aml for a couple weeks now.

**Comment by Ken-Lo** [comment]
@harrison Yeah sure, no probs at all, will do this next week following the template you provided above. Will tag you on the PR!

**Comment by Ken-Lo** [comment]
Closed by https://github.com/gocardless/splash-pages/pull/190
