### ISSUE TITLE
Typo on Bluesky Business story page

### ISSUE THREAD

**Issue by jamesshedden** [gocardless/splash-pages#196]
`We&quo;re` --> `We're` 

spotted at `/stories/bluesky-business/`:

![screen shot 2015-06-08 at 15 53 34](https://cloud.githubusercontent.com/assets/883598/8037604/a4ddb38e-0df6-11e5-896a-c5e689148f09.png)

**Comment by jackfranklin** [comment]
Good spot, fixing

**Comment by jamesshedden** [comment]
Nice @jackfranklin, thanks to @yoshiotakeuchi for spotting

**Comment by yoshiotakeuchi** [comment]
You're welcome @jackfranklin

**Comment by jackfranklin** [comment]
https://github.com/gocardless/splash-pages/pull/197
