### ISSUE TITLE
Footer text in title case on splash pages, caps on guides

### ISSUE THREAD

**Issue by jackfranklin** [gocardless/splash-pages#203]
All the footer links on the splash pages are in regular case, but on the guides https://gocardless.com/guides they are in all capitals. I have no opinion on which one is best, but we should pick one and stick with it.

@harrison @anothertompetty what do you think?

Thanks to @jutta-frieden for spotting it!

**Comment by samjewell** [comment]
Ahh yeah, I was the one to change it to Title Case on the Splash pages, when I made the country switcher component - @anothertompetty felt Title Case went better with the country picker (which I think is similar? ie not all caps?)
So I think we should also switch to title case on the guides as well now...

**Comment by jutta-frieden** [comment]
I agree with Sam, Title Case feels more appropriate than SHOUTING CAPS. ;-)
Thanks Jack for starting the discussion.
Cheers

---
Jutta Frieden
jutta.frieden@gmail.com
+44 7428214431

**Comment by Ken-Lo** [comment]
This is dealt with in https://github.com/gocardless/guides/pull/222 (updating the guides footer to match the splash page footer).

**Comment by jackfranklin** [comment]
@Ken-Lo awesome, thank you! :+1:
