### ISSUE TITLE
Consider using non-SVG flags

### ISSUE THREAD

**Issue by Ken-Lo** [gocardless/splash-pages#300]
We currently use SVG vector flags in the footer of the website. While this works OK for geometric flags (e.g. the French flag is 834 bytes in size), other flags are much more complex (e.g. the Spanish flag is 240KB in size when in SVG format). This is slightly overkill seeing as we only render the flag at 35x23 pixels (would be 492 bytes if we were to render the flag to PNG).

**Comment by Ken-Lo** [comment]
@harrison Any objections to us doing this, bearing in mind the flag is embedded on splash pages in every language?

**Comment by harrison** [comment]
Yeah probably makes sense, would be nice to have custom small versions of flags, resizing the Spanish one would make it look a bit shit.

For the current Spanish could we use the simplified one? https://commons.wikimedia.org/wiki/File:Simplified_Flag_of_Spain_(civil_variant).svg

**Comment by Ken-Lo** [comment]
See https://github.com/gocardless/splash-pages/pull/303
