### ISSUE TITLE
Define constants for number of customers, number of countries, etc.

### ISSUE THREAD

**Issue by Ken-Lo** [gocardless/splash-pages#351]
Throughout the splash pages, there are several numbers we refer to a lot e.g. # of customers, # of countries supported, etc. Rather than having to go through the every individual page, it would be good to define some global constants (this would save us having to define it in en.js, fr.js, de.js, es.js and in every single language)/

I'm thinking it would probably be easiest if we define a new messages file for non-localised values. This would sit one-level above en.js, fr.js, etc. Something like:

* global.js (number of customers e.g. 13,000)
  * en.js
    * en-GB.js
  * fr.js (can overwrite based on locale e.g. 13.000)
    * fr-FR.js

**Comment by Ken-Lo** [comment]
@harrison Any thoughts on the above or on the best way to do this?
/cc @octaveauger

**Comment by harrison** [comment]
ah yeah, maybe add `shared.js` to `app/messages` and add it to the merge here https://github.com/gocardless/splash-pages/blob/dev/config/messages.js#L33

**Comment by Ken-Lo** [comment]
See https://github.com/gocardless/splash-pages/pull/357
