### ISSUE TITLE
Expanding a drop-down nav list stops most links further down the page from working

### ISSUE THREAD

**Issue by jacobpgn** [gocardless/splash-pages#394]
Expanding a drop-down, ie:
![screen shot 2015-01-23 at 17 59 19](https://cloud.githubusercontent.com/assets/6728978/5879764/dc70780a-a329-11e4-894c-f8badf6fa402.png)

appears to kill most links on the page - clicking a link scrolls you to the top of the page but doesn't change the page.

Doesn't seem to affect _all_ links, but consistently blocks the footer section at least:
![screen shot 2015-01-23 at 18 01 52](https://cloud.githubusercontent.com/assets/6728978/5879787/0fd87026-a32a-11e4-8017-2b219690e431.png)

**Comment by jamesshedden** [comment]
Fixed by popover refactor work here https://github.com/gocardless/splash-pages/pull/405

**Comment by samjewell** [comment]
@jamesshedden woop! good spot closing this issue
